
/* **** DO NOT EDIT - this file is generated by ARChitect2 ****
 *
 * Description: Header file declaring the compiler extensions for eia components
 */

#ifndef H_DSP_CONFIG
#define H_DSP_CONFIG

#define DSP_TRIG_PRESENT

#endif  /* H_DSP_CONFIG */
